FuzzydoDB/fuzzydoDB/config/routes.rb
Rails.application.routes.draw do

  resources :posts
  scope "(:locale)", locale: /es|en/ do

    root 'home#index'
    get 'home' => 'home#index'

    scope 'home' do
      get 'member/:id' => 'home#member'
    end

    get 'foro' => 'foro#index'

    scope 'foro' do
      get 'member/:id' => 'foro#index'
    end

    get 'onlinetest' => 'onlinetest#index'

    scope 'onlinetest' do
    end

    get 'articles' => 'articles#index' 

    scope 'articles' do
      get 'articles' => 'articles#new'
      post 'articles' => 'articles#create'
      get 'articles/:id' => 'articles#show'
      get 'articles/:id/edit' => 'articles#edit'
      put 'articles/:id' => 'articles#update'
      delete 'articles/:id' => 'articles#delete'
    end 

    get 'about' => 'about#index'

    scope 'about' do
      get 'history' => 'about#history'
      get 'members' => 'about#members'
      get 'member/:id' => 'about#member'
      get 'dev/:id' => 'about#dev'
    end

    devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }

    post 'users/validateUsername/' => 'users#validate_username', :defaults => { :format => 'json' }
    post 'users/validateEmail/' => 'users#validate_email', :defaults => { :format => 'json' }

    scope 'profile' do
      delete 'destroy_avatar', to: 'users#destroy_avatar'
      put 'update_avatar', to: 'users#update_avatar'
      get ':username/editPhoto', to: 'users#edit_profile_photo'
      get ':username', to: 'users#show'
      put ':id', to: 'users#update'
      get ':username/edit', to: 'users#edit'
      get ':username/update_password', to: 'users#edit_password'
      put ':username/update_password', to: 'users#update_password'
    end

    scope "admin" do
      get 'transferRole' => 'users#show_transfer_role'
      post 'transferRole' => 'users#transfer_role'
      put 'users/changeRoles' => 'users#change_roles'
      resources :users, except: [:show, :create] #show is handled in profile, create in registrations
    end
  end

end

FuzzydoDB/fuzzydoDB/app/views/shared/_footer.html.erb
<% if @isHome %>

<footer class="footer-container site-footer container-fluid">

<% else %>

<footer class="footer-container site-footer footer-sidebar-fluid">

<% end -%>

  <div class="row">
  <div class="col-xs-1"><%= image_tag("logoUSB.png", width: "80px", height: "50px") %></div>
  <div class="col-xs-5 info"><%=t 'university' %> - <%=t 'country' %></div>
  <div class="col-xs-6 legal"><%=t 'footer.info' %></div>
  </div>
</footer>

FuzzydoDB/fuzzydoDB/app/views/shared/_header.html.erb
<header class="header-fixed w3-card-2">
  <div class="header-x-scroll">
    <div class="container-fluid header-container">

      <div class="row">
        <div class="col-xs-2 logo">
          <%= link_to image_tag("fuzzydodb.png", width: "190px", height: "50px"), controller: "/home" %>
        </div>
        <div class="col-xs-10 header-right-container">
          <div class="top-options-container">
            <% if !current_user %>
              <button id="register-btn" type="button" class="btn btn-default" data-toggle="modal" data-target="#modalRegister"> <%=t('header.register')%> </button>
              <button id="login-btn" type="button" class="btn btn-default" data-toggle="modal" data-target="#modalLogin"><span class="glyphicon glyphicon-log-in"></span> <%= t('header.login') %></button>
            <% else %>
              <div class="header-user-info">
                <%= link_to raw("<span class=\"glyphicon glyphicon-user\"></span> <strong>#{current_user.display_name}</strong>"), user_path(current_user) %>

              </div>
              <%= link_to raw("<span class=\"glyphicon glyphicon-log-out\"></span> #{t('header.logout')}"), destroy_user_session_path, id: "logout-btn",class: "btn btn-default", :method => :delete %>
            <% end %>
            <div class="input-group">
              <input type="text" name="search" class="form-control" placeholder="<%=t 'header.search' %>">
              <span class="input-group-btn">
                <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-search"/></button>
              </span>
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="header-menu">
      <ul class="main-menu-bar w3-light-grey">
      <% menu_tags = [t("header.menu.home"),
        t("header.menu.team"),
        t("header.menu.download"),
        t("header.menu.api"),
        t("header.menu.doc"),
        t("header.menu.onlineTests"),
        t("header.menu.performance"),
        t("header.menu.community"),
        t("header.menu.foro")]
      -%>

      <%# TODO: controller names missing !!!!!!! %>
      <% menu_controllers = ["home","about","home","home","articles","onlinetest","home","home","foro"] -%>

      <% menu_tags.each_with_index do |tag, i| -%>
        <li class="w3-hover-teal" >
          <%= link_to(tag, controller: "/"+menu_controllers[i]) %>
        </li>
      <% end -%>
        <!-- Cable 
        <li class="w3-hover-teal">
          <a href="http://127.0.0.1:3000">FORO</a>
        </li>-->

        <li class="w3-hover-teal w3-right w3-dropdown-hover">
          <a>
            <span class="glyphicon glyphicon-globe language-icon"></span>
            <%= t("header.menu.language") %>
          </a>

          <div class="w3-dropdown-content w3-light-grey w3-card-4">
            <%= link_to("English", url_for(:locale => "en"), {:class => "w3-hover-teal"}) %>
            <%= link_to("Español", url_for(:locale => "es"), {:class => "w3-hover-teal"}) %>
          </div>
        </li>
      </ul>
    <div>
</header>

FuzzydoDB/fuzzydoDB/app/views/shared/_modal_session.html.erb
<% modalWindowIds.each do |id| %>
  <div class="modal fade" id="modal<%= id.capitalize %>" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-md" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">
            <% if id.eql? "password" %>
              <%= t('header.forgot.password')%>
            <% else %>
              <%= t("header.#{id}")%>
            <% end %>
          </h4>
        </div>
        <%= render :partial => "shared/modals/#{id}" %>
      </div>
    </div>
  </div>
<% end %>

FuzzydoDB/fuzzydoDB/app/views/shared/_plain_content.html.erb
<h1>
  <%=t(title_token)-%>
</h1>
<div class="container-fluid text-content">
  <%=t(content_token)-%>
</div>

FuzzydoDB/fuzzydoDB/app/views/shared/_sidebar.html.erb
<div class="content-left">
  <ul class="left-navigation">
  <% sidebar_bar_items.each_with_index do |item,i| %>
    <li>
      <a href="<%= links[i] %>" class="<% if (sidebar_bar_items[i] == active_item) %> active-item <% end -%>">
       <%=t(token_sidebar_namespace + item)%>
      </a>
    </li>
  <% end -%>
  </ul>
</div>

FuzzydoDB/fuzzydoDB/app/views/shared/_user_photo.html.erb
<% photo = "default.png" if photo.blank?  %>
<% photo = folder + photo if !photo.blank? && !folder.blank? %>
<% html_att = {} if html_att.blank? %>
<%= image_tag(photo, width: "200px", height: "200px", :class =>"user-bio-img", :data => html_att) %>

FuzzydoDB/fuzzydoDB/app/views/shared/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>

<body class="error-page">
  <div class="error-content">
      <h1><%= t(@error) %> :(</h1>
      <%= image_tag("confused_pet.png")%>
  </div>
</body>
</html>