FuzzydoDB/fuzzydoDB/config/routes.rb
Rails.application.routes.draw do

  resources :posts
  scope "(:locale)", locale: /es|en/ do

    root 'home#index'
    get 'home' => 'home#index'

    scope 'home' do
      get 'member/:id' => 'home#member'
    end

    get 'foro' => 'foro#index'

    scope 'foro' do
      get 'member/:id' => 'foro#index'
    end

    get 'onlinetest' => 'onlinetest#index'

    scope 'onlinetest' do
    end

    get 'articles' => 'articles#index' 

    scope 'articles' do
      get 'articles' => 'articles#new'
      post 'articles' => 'articles#create'
      get 'articles/:id' => 'articles#show'
      get 'articles/:id/edit' => 'articles#edit'
      put 'articles/:id' => 'articles#update'
      delete 'articles/:id' => 'articles#delete'
    end 

    get 'about' => 'about#index'

    scope 'about' do
      get 'history' => 'about#history'
      get 'members' => 'about#members'
      get 'member/:id' => 'about#member'
      get 'dev/:id' => 'about#dev'
    end

    devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }

    post 'users/validateUsername/' => 'users#validate_username', :defaults => { :format => 'json' }
    post 'users/validateEmail/' => 'users#validate_email', :defaults => { :format => 'json' }

    scope 'profile' do
      delete 'destroy_avatar', to: 'users#destroy_avatar'
      put 'update_avatar', to: 'users#update_avatar'
      get ':username/editPhoto', to: 'users#edit_profile_photo'
      get ':username', to: 'users#show'
      put ':id', to: 'users#update'
      get ':username/edit', to: 'users#edit'
      get ':username/update_password', to: 'users#edit_password'
      put ':username/update_password', to: 'users#update_password'
    end

    scope "admin" do
      get 'transferRole' => 'users#show_transfer_role'
      post 'transferRole' => 'users#transfer_role'
      put 'users/changeRoles' => 'users#change_roles'
      resources :users, except: [:show, :create] #show is handled in profile, create in registrations
    end
  end

end

FuzzydoDB/fuzzydoDB/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # include Mongoid::Document
  # include SimpleEnum::Mongoid
  # # Include default devise modules. Others available are:
  # # :confirmable, :lockable, :timeoutable and :omniauthable

  enum role: [:user, :member, :admin, :super_member]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

   devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

  # ## Database authenticatable
  # field :email,              type: String, default: ""
  # field :encrypted_password, type: String, default: ""

  # ## Recoverable
  # field :reset_password_token,   type: String
  # field :reset_password_sent_at, type: Time

  # ## Rememberable
  # field :remember_created_at, type: Time

  # ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  #field :username, type: String
  #field :name, type: String
  #as_enum :role, [:user, :member, :admin, :super_member], field: { :default => 0 }
  #field :photo, type: String
  #field :institution, type: String
  #field :occupation, type: String
  #field :country, type: String
  
  validates :username, presence: true, uniqueness: true, format: /\A\w*\z/
  validates :name, presence: true
  validates :role_cd, inclusion: { in: User.roles.values }
  before_validation :drop_the_case
  mount_uploader :avatar, AvatarUploader

  def country_name
    name = ISO3166::Country.new(country)
    name.translations[I18n.locale.to_s] || country
  end

  def self.exists_username?(username)
    self.where(username: username.downcase).exists?
  end

  def self.exists_email?(email)
    self.where(email: email.downcase).exists?
  end


  def self.find_by_username username
    self.where(username: username)[0]
  end

  def admin_or_super_member?
    self.admin? || self.super_member?
  end

  # Admin and super_member cannot be set to other users
  def self.setteable_role?(int_role)
    !(User.roles.values_at(:admin, :super_member).include? int_role)
  end

  # Changes the roles of several users
  def self.change_roles(changed_users)

    unless changed_users.nil?

      users = self.all.entries

      changed_users.each do |changed_user|
        self.change_single_user_role(users, changed_user)
      end

    end
  end

  private

  # Changes the role of a single user
  # Admin and super user's roles cannot be changed and
  # user and member's roles cannot be set to admin or super member
 def self.change_single_user_role(users, changed_user)

   int_changed_role = Integer(changed_user["role"])
    user = users.find { |u| u.username == changed_user["username"] }

    if !user.admin_or_super_member? && self.setteable_role?(int_changed_role)

      user.role = int_changed_role
      user.save!
    end
  end

  def drop_the_case
    self.username = self.username.downcase unless self.username.nil?
    self.email = self.email.downcase unless self.email.nil?
  end
end

FuzzydoDB/fuzzydoDB/app/controllers/users_controller.rb
class UsersController < ApplicationController

  include ProfileHelper

  before_action :set_user_by_id, only: [:update, :destroy, :transfer_role]
  before_action :set_user_by_username, only: [:show, :edit, :edit_profile_photo, :update_password]
  protect_from_forgery except: [:validate_username, :validate_email]
  before_filter :admin_or_super_member_only!, only: [:index, :destroy, :transfer_role, :show_transfer_role]
  before_filter :super_member_only!, only: [:change_roles]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /profile/1
  # GET /profile/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /profile/1/edit
  def edit
    current_user_only! @user
  end

  # GET /profile/1/editPhoto
  def edit_profile_photo
    current_user_only! @user
  end

  def update_password
    updated = @user.update_with_password(user_params)
    flash.clear
    if updated
      flash[:success] = t("user-profile.edit-password.success")
      sign_in @user, :bypass => true
    elsif !updated
      flash[:danger] = t("user-profile.edit-password.wrong-old-password")
    end
    render "edit_password"
  end

  def edit_password
    @user = current_user
  end

  # PATCH/PUT /profile/1
  # PATCH/PUT /profile/1.json
  def update
    respond_to do |format|
      current_user_only! @user
      if @user.update(user_params)
        format.html { redirect_to profile_path(@user.username)}
        format.json { render :show, status: :ok, location: profile_path(@user.username)}
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profile/update_avatar
  # PATCH/PUT /profile/update_avatar.json
  def update_avatar

    @user = current_user
    @user.avatar = params[:file]

    @user.save!

    respond_to do |format|
      format.html { redirect_to profile_path(@current_user.username) }
      format.json { render :show, status: :ok }
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  # Admins and super_members cannot be destroyed
  def destroy

    unless @user.admin_or_super_member?
      @user.destroy
      flash[:delete_notice] = @user.username
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # DELETE /profile/destroy_avatar
  def destroy_avatar
    @user = current_user
    @user.remove_avatar!
    @user.save!
    User.where(username: @user.username).update(avatar: nil)

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # If the user doesn't exists, then it is valid
  def validate_username
    username = params[:username]
    user_exists = !User.exists_username?(username)
    respond_to do |format|
      format.json { render json: user_exists }
    end
  end

  def validate_email
    if !current_user.nil? && current_user.email.eql?(params[:email])
      user_exists = true
    else
      email = params[:email]
      user_exists = !User.exists_email?(email)
    end

    respond_to do |format|
      format.json { render json: user_exists }
    end
  end

  #PATCH/PUT
  def change_roles
    changed_users = params[:users]
    User.change_roles(changed_users)

    respond_to do |format|

      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # GET
  def show_transfer_role
    if current_user.super_member?
      @users = User.where(role_cd: User.roles[:member])
    else
      @users = User.where(role_cd: User.roles[:user])
    end
  end

  #POST
  # current user transfer his role
  # super member can only transfer his role to member
  # admin to users
  def transfer_role

    if !@user.admin_or_super_member?
      @user.role = current_user.role

      if current_user.super_member?
        current_user.member!
      else
        current_user.user!
      end

      @user.save!
      current_user.save!
    end

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_by_username
      @user = User.find_by(username:params[:username])
      if @user.nil?
        @error = "errors.not_found"
        render(:file => File.join(Rails.root, 'app/views/shared/error.html'), :status => 404, :layout => false)
      end
    end

    def set_user_by_id
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :name, :email, :occupation, :institution, :country, :password, :password_confirmation, :current_password)
    end
end

FuzzydoDB/fuzzydoDB/app/helpers/users_helper.rb
module UsersHelper
end

FuzzydoDB/fuzzydoDB/app/views/users/_admin_sidebar.html.erb
<% @sidebar_bar_items = ["user-list", "transfer-role"] %>
<% @token_sidebar_namespace = "admin.menu." %>
<% @links = [ url_for(controller: controller_name, action: "index"),
              url_for(controller: controller_name, action: "transfer_role")] %>

<%= render :partial => "shared/sidebar",
    locals: { sidebar_bar_items: @sidebar_bar_items,
              active_item: active_item,
              token_sidebar_namespace: @token_sidebar_namespace,
              links: @links } %>

FuzzydoDB/fuzzydoDB/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FuzzydoDB/fuzzydoDB/app/views/users/_show_profile.html.erb
<div class="row">
  <div class="container-fluid member-container member-bio-header">
  <div class="col-xs-4">
    <%= render :partial => "shared/user_photo", locals: { photo: @user.avatar.url, folder: nil} %>
  </div>
  <div class="col-xs-8 member-bio-name">
    <div>
      <%= @user.name %>
    </div>
  </div>
  </div>
  <% field = ["name", "username", "email", "institution", "occupation", "country"] %>
  <% field.each do |tag| %>
  <div class="col-xs-3 show-profile-field">
    <strong><%= t("user-profile.#{tag}") %>:</strong>
  </div>
  <div class="col-xs-3 show-profile-field" id="user_<%= tag %>">
    <%= field_value = @user.read_attribute tag
        if field_value.present?
          if tag.eql? "country"
            @user.country_name
          else
            field_value
          end
        else
          t("user-profile.none-especified")
        end
     %>
  </div>
  <% end %>
</div>

FuzzydoDB/fuzzydoDB/app/views/users/_user_sidebar.html.erb
<% @sidebar_bar_items = ["show"] %>
<% @sidebar_bar_items = @sidebar_bar_items + ["edit", "edit_photo", "update_password"] if @user == current_user %>
<% @token_sidebar_namespace = "user-profile.menu." %>
<% @links = [ url_for(controller: controller_name, action: "show") ]%>
<% @links = @links + [url_for(controller: controller_name, action: "edit"),
                      url_for(controller: controller_name, action: "edit_profile_photo"),
                      url_for(controller: controller_name, action: "edit_password")] if @user == current_user %>

<%= render :partial => "shared/sidebar",
    locals: { sidebar_bar_items: @sidebar_bar_items,
              active_item: active_item,
              token_sidebar_namespace: @token_sidebar_namespace,
              links: @links } %>

FuzzydoDB/fuzzydoDB/app/views/users/edit.html.erb
<% title(t "user-profile.edit.title") %>

<div class="content-wrapper" ng-controller="ProfileController">

  <%= render :partial => "user_sidebar",
        locals: { active_item: "edit"} %>

  <div class="ng-hide" id="user_username" value="<%= @user.username %>">

  </div>

  <div class="content-right">
    <h1><%= t("user-profile.edit.title") %></h1>
    <%= form_for(@user, method: :put, :url => profile_path(@user.id), :html => {:novalidate => true, "name" => "editForm"}) do |f| %>
      <%= devise_error_messages! %>

    <!-- name field -->

    <div class="field">
      <div id="editNameError" class="error-messages error" ng-messages="editForm['user[name]'].$error"
        ng-if="editForm['user[name]'].$touched || editForm.$submitted">
        <div ng-message="required"> <%= t("mongoid.errors.models.user.attributes.name.blank")%> </div>
      </div>
      <p>
        <%= f.label :name, t("user-profile.name") %>
        <%= f.text_field :name, class: "w3-input",
            "ng-model" => "user.name", "ng-model-options" => "{ updateOn: 'blur' }",
            :required => true%>
      </p>
      <span class="icon glyphicon"
        ng-class="{'error glyphicon-remove' : editForm['user[name]'].$invalid &&
          (editForm['user[name]'].$touched || editForm.$submitted),
          'sucess glyphicon-ok' : editForm['user[name]'].$valid}">
      </span>
    </div>

    <!-- email field -->

    <div class="field">
      <div id="editEmailError" class="error-messages error" ng-messages="editForm['user[email]'].$error"
        ng-if="editForm['user[email]'].$touched || editForm.$submitted">
        <div ng-message="required"> <%= t("mongoid.errors.models.user.attributes.email.blank")%> </div>
        <div ng-message="email"> <%= t("errors.invalidEmail") %> </div>
        <div ng-message="emailTaken"> <%= t("mongoid.errors.models.user.attributes.email.taken")%> </div>
      </div>
      <p>
        <%= f.label :email, t("user-profile.email") %>
        <%= f.email_field :email, class: "w3-input",
          "ng-model" => "user.email", "ng-model-options" => "{ updateOn: 'blur' }",
          "email-taken-validator" => true, :required => true %>
      </p>
      <span class="icon glyphicon"
        ng-class="{'error glyphicon-remove' : editForm['user[email]'].$invalid &&
          (editForm['user[email]'].$touched || editForm.$submitted),
          'sucess glyphicon-ok' : editForm['user[email]'].$valid,
          'icon-spin glyphicon-refresh' :  editForm['user[email]'].$pending}">
      </span>
    </div>

    <!-- occupation field -->

    <div class="field">
      <p>
        <%= f.label :occupation, t("user-profile.occupation") %>
        <%= f.text_field :occupation, class: "w3-input",
            "ng-model" => "user.occupation", "ng-model-options" => "{ updateOn: 'blur' }",
            :required => true%>
      </p>
    </div>

    <!-- country field -->

    <div class="field">
      <p>
        <%= f.label :country, t("user-profile.country") %>
        <div class="">
          <%= f.country_code_select :country, {selected: @user.country},
              "ng-model" => "user.country", "ng-model-options" => "{ updateOn: 'blur' }",
              :required => true%>
        </div>
      </p>
    </div>

    <!-- institution field -->

    <div class="field">
      <p>
        <%= f.label :institution, t("user-profile.institution") %>
        <%= f.text_field :institution, class: "w3-input",
            "ng-model" => "user.institution", "ng-model-options" => "{ updateOn: 'blur' }",
            :required => true%>
      </p>
    </div>

      <div class="actions"><%= f.submit t("labels.save_changes"), :class => "btn btn-default",
        "ng-click" => "sendProfile($event)" %></div>
    <% end %>
  </div>
</div>

FuzzydoDB/fuzzydoDB/app/views/users/edit_password.html.erb
<% title(t 'user-profile.menu.update_password') %>

<div class="content-wrapper" ng-controller="RegistrationController">

  <%= render :partial => "user_sidebar",
        locals: { active_item: "update_password"} %>

  <div class="content-right">
    <h1><%= t("user-profile.edit-password.title") %></h1>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%=key%> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= value %>
      </div>
    <% end %>


    <%= form_for(@user, :url => { :action => "update_password" }, :method => :PUT,
        :html => {:novalidate => true, "name" => "changePasswordForm"} ) do |f| %>

      <!-- actual password field -->

      <div class="field">
        <div id="currentPasswordError" class="error-messages error" ng-messages="changePasswordForm['user[current_password]'].$error"
          ng-if="changePasswordForm['user[current_password]'].$touched || changePasswordForm.$submitted">
          <div ng-message="required"> <%= t("mongoid.errors.models.user.attributes.password.blank")%> </div>
          <div ng-message="minlength"> <%= t("mongoid.errors.models.user.attributes.password.too_short")%> </div>
        </div>
        <p>
          <%= f.label :none, t("user-profile.current-password") %>
          <%= f.password_field :current_password, autocomplete: "off", class: "w3-input",
            "ng-model" => "user.currentPassword", "ng-model-options" => "{ updateOn: 'blur' }",
            "ng-minlength" => 6, :required => true %>
        </p>

        <span class="icon glyphicon"
          ng-class="{'error glyphicon-remove' : changePasswordForm['user[current_password]'].$invalid &&
            (changePasswordForm['user[current_password]'].$touched || changePasswordForm.$submitted),
            'sucess glyphicon-ok' : changePasswordForm['user[current_password]'].$valid}">
        </span>
      </div>

      <!-- new password field -->

      <div class="field">
        <div id="passwordError" class="error-messages error" ng-messages="changePasswordForm['user[password]'].$error"
          ng-if="changePasswordForm['user[password]'].$touched || changePasswordForm.$submitted">
          <div ng-message="required"> <%= t("mongoid.errors.models.user.attributes.password.blank")%> </div>
          <div ng-message="minlength"> <%= t("mongoid.errors.models.user.attributes.password.too_short")%> </div>
        </div>
        <p>
          <%= f.label :none,  t("user-profile.password") %>
          <%= f.password_field :password, autocomplete: "off", class: "w3-input",
            "ng-model" => "user.password", "ng-model-options" => "{ updateOn: 'blur' }",
            "ng-minlength" => 6, :required => true %>
        </p>

        <span class="icon glyphicon"
          ng-class="{'error glyphicon-remove' : changePasswordForm['user[password]'].$invalid &&
            (changePasswordForm['user[password]'].$touched || changePasswordForm.$submitted),
            'sucess glyphicon-ok' : changePasswordForm['user[password]'].$valid}">
        </span>

      </div>

      <!-- password confirmation field -->

      <div class="field">

        <div id="passwordConfirmationError" class="error-messages error"
          ng-messages="changePasswordForm['user[password_confirmation]'].$error"
          ng-if="changePasswordForm['user[password_confirmation]'].$touched || changePasswordForm.$submitted">
          <div ng-message="required"> <%= t("mongoid.errors.models.user.attributes.password.blank")%> </div>
          <div ng-message="equalPasswords">
            <%= t("mongoid.errors.models.user.attributes.password_confirmation.confirmation")%>
          </div>
        </div>

        <p>
          <%= f.label :none,  t("user-profile.password-confirmation") %>
          <%= f.password_field :password_confirmation, autocomplete: "off", class: "w3-input",
            "ng-model" => "user.passwordConfirmation", "ng-model-options" => "{ updateOn: 'blur' }",
            "equal-passwords" => "user.password", :required => true %>
        </p>

        <span class="icon glyphicon"
          ng-class="{'error glyphicon-remove' : changePasswordForm['user[password_confirmation]'].$invalid &&
            (changePasswordForm['user[password_confirmation]'].$touched || changePasswordForm.$submitted),
            'sucess glyphicon-ok' : changePasswordForm['user[password_confirmation]'].$valid}">
        </span>

      </div>
      <div class="action_container">
        <%= f.submit t("labels.save_changes"), :class => "btn btn-default" %>
      </div>
    <% end %>
  </div>
</div>

FuzzydoDB/fuzzydoDB/app/views/users/edit_profile_photo.html.erb
<% title(t "user-profile.edit-photo.title") %>

<%= render :partial => "user_sidebar",
        locals: { active_item: "edit_photo"} %>

<div class="content-right">
    <h1><%= t("user-profile.edit-photo.title") %></h1>

    <div ng-controller="ProfilePhotoController">
      <div class="fluid-container">
        <div class="row edit-photo-container">
          <div class="col-xs-6">
            <div class="cropArea">
              <img-crop image="myImage" result-image="myCroppedImage" result-image-size="300"
                area-min-size="40" ></img-crop>
            </div>
          </div>
          <div class="col-xs-6 preview-photo">
            <%= render :partial => "shared/user_photo",
                locals: { photo: @user.avatar.url, folder: nil, html_att: {"ng-src" => "{{myCroppedImage}}"}} %>
            <div class="preview-text"> <%= t("labels.preview") %> </div>

          </div>
        </div>
      </div>

      <div><%= t("labels.select_img") %></div>

      <%# Style input[type=file]:
        http://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3/ %>

      <div class="row">
        <div class="fluid-container">
          <div class="col-xs-6">
            <div class="input-group">
              <label class="input-group-btn">
                <span class="btn btn-default">
                  <%= t("labels.browse") %> <input type="file" id="fileInput" style="display: none;">
                </span>
              </label>
              <input type="text" class="form-control disabled" readonly ng-model="selectedFile">
            </div>
          </div>
          <div class="col-xs-6 text-right">
            <span class="btn btn-non-primary" ng-click="deletePhoto()"> <%= t("labels.delete") %> </span>
            <span class="btn btn-non-primary" ng-click="resetPhoto()" ng-disabled="!areChangesMade">
              <%= t("labels.discard") %>
            </span>
            <span class="btn btn-default" ng-click="sendPhoto()"><%= t("labels.save_changes") %> </span>
          </div>
        </div>
      </div>
    </div>
</div>

FuzzydoDB/fuzzydoDB/app/views/users/index.html.erb
<% title t("admin.user-list") %>

<div class="content-wrapper">

  <%= render :partial => "admin_sidebar",
        locals: { active_item: "user-list"} %>

  <div class="content-right" ng-controller="UserController">
    <h1><%= t("admin.user-list") %></h1>

    <% unless flash[:delete_notice].nil? %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= t("admin.delete-response-alert", user: flash[:delete_notice]) %>
      </div>
    <% end %>

    <div class="table-responsive" ng-form name="userTable">
      <table id="userTable" class="table table-striped w3-hoverable table-bordered">
        <thead>
          <tr>
            <th><%= t("user.username") %></th>
            <th><%= t("user.name") %></th>
            <th><%= t("user.email") %></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr class="w3-hover-teal" ng-class="{ 'font-bold' : userTable.<%= user.username %>.$dirty }">
              <td><%= user.username %></td>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= link_to t("labels.show"), profile_path(user.username)%></td>
              <td>
                <div class="<%= "disabled" if user.admin? || user.super_member? %>">
                  <a data-toggle="modal" data-target="#deleteConfirmationModal" data-username="<%= user.username %>" data-delete-url="<%= url_for user%>" class="<%= "disabled" if user.admin? || user.super_member? %>">
                    <%= t("labels.delete")%>
                  </a>
                </div>
              </td>
              <td>
                <select class="selectpicker" <%= "disabled" if current_user.admin? || user.admin_or_super_member? %>
                  ng-model="users.<%= user.username %>" ng-init="users.<%= user.username %> = '<%= user.role_cd %>'"
                  name="<%= user.username %>">
                  <% User.roles.each do |role| %>
                    <option value="<%= role[1] %>" <%= "disabled" if role[0] == "admin" || role[0] == "super_member" %>>
                      <%= t("user.role." + role.first) %>
                    </option>
                  <% end %>
                </select>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <% if current_user.super_member? %>
      <a id="save-changes-btn" class="btn btn-default" ng-click="saveRoles()" ng-disabled="userTable.$pending">
        <span class="glyphicon icon-spin glyphicon-refresh" ng-if="userTable.$pending"></span>
        <%= t("labels.save_changes") %>
      </a>
      <% end %>

    </div>
  </div>
</div>

<%# content is added using js %>
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content w3-container">
      <div class="modal-body modal-delete-user">
      </div>
      <div class="modal-footer">
        <a class="btn btn-non-primary" data-dismiss="modal"><%= t("labels.close") %></a>
        <a id="deleteBtn" class="btn btn-danger" data-method="delete"><%= t("labels.delete") %></a>
      </div>
    </div>
  </div>
</div>

FuzzydoDB/fuzzydoDB/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

FuzzydoDB/fuzzydoDB/app/views/users/show.html.erb
<% title(t "user-profile.show.title") %>

<div class="content-wrapper">

  <%= render :partial => "user_sidebar",
        locals: { active_item: "show"} %>

  <div class="content-right">
    <h1><%= t("user-profile.show.title") %></h1>
    <%= render :partial => "users/show_profile" %>

  </div>
</div>