FuzzydoDB/foroFuzzydoDB/config/routes.rb
Rails.application.routes.draw do
	scope '/(:locale)', defaults: { locale: 'es' }, constraints: { locale: /en|es|pt-br/ } do
		root to: 'home#index'
		devise_for :users
		get 'foro' => 'foro#index'

		scope 'foro' do
	      get 'member/:id' => 'foro#member'
	    end
		# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
		resources :users, only: [:show]
		mount Thredded::Engine => '/forum'
	end
end

FuzzydoDB/foroFuzzydoDB/app/views/shared/modals/_login.html.erb
<div ng-controller="LoginController">

<%= form_for(resource, as: resource_name, url: session_path(resource_name),
    :html => {:class => "w3-container", :novalidate => true, "name" => "loginForm"}) do |f| %>
  <div class="modal-body">

    <!-- email field -->

    <div class="field">
      <div id="loginEmailError" class="error-messages error" ng-messages="loginForm['user[email]'].$error"
        ng-if="loginForm['user[email]'].$touched || loginForm.$submitted">
        <div ng-message="required"> <%= t("mongoid.errors.models.user.attributes.email.blank")%> </div>
        <div ng-message="email"> <%= t("errors.invalidEmail") %> </div>
      </div>

      <p>
        <%= f.label :email %>
        <%= f.email_field :email, :class => "w3-input",
          "ng-model" => "loginUser.email", "ng-model-options" => "{ updateOn: 'blur' }",
          :required => true %>
      </p>

      <span class="icon error glyphicon glyphicon-remove"
        ng-if="loginForm['user[email]'].$invalid &&
          (loginForm['user[email]'].$touched || loginForm.$submitted)"></span>

    </div>

    <!-- password field -->

    <div class="field">
      <div id="loginPassError" class="error-messages error" ng-messages="loginForm['user[password]'].$error"
        ng-if="loginForm['user[password]'].$touched || loginForm.$submitted">
        <div ng-message="required"> <%= t("mongoid.errors.models.user.attributes.password.blank")%> </div>
      </div>

      <p>
        <%= f.label :password %>
        <%= f.password_field :password, autocomplete: "off",
          :class => "w3-input", "ng-model" => "loginUser.password", "ng-model-options" => "{ updateOn: 'blur' }",
          :required => true %>
      </p>

      <span class="icon error glyphicon glyphicon-remove"
        ng-if="loginForm['user[password]'].$invalid &&
          (loginForm['user[password]'].$touched || loginForm.$submitted)"></span>

    </div>

    <!-- remember me checkbox -->

    <% if devise_mapping.rememberable? -%>
      <p>
        <%= f.check_box :remember_me, "ng-model" => "loginUser.rememberMe" %>
        <%= f.label t("activerecord.attributes.user.remember_me") %>
      </p>
    <% end -%>
    <% @modalAction = "login" %>
    <%= render 'devise/shared/links', :locals => { :modalAction => @modalAction } %>
  </div>
  <div class="modal-footer">

    <span id="loginError" ng-if="loginError" class="error login-error-message">
      <span class="glyphicon glyphicon-remove"></span>
      <%= t("devise.failure.not_found_in_database")%>
    </span>

    <a class="btn btn-non-primary" data-dismiss="modal"> <%= t("labels.cancel") %> </a>
    <%= f.submit t("header.login"), :id => 'send-login-btn',  :class => "btn btn-default",
      "ng-click" => "submitLogin($event)", "ng-disabled" => "loginForm.$pending" %>
  </div>
<% end %>

</div>

FuzzydoDB/foroFuzzydoDB/app/views/shared/modals/_lost_password.html.erb
<div class="modal-body">
  <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
    <%= devise_error_messages! %>

    <div class="field">
      <%= f.label t("activerecord.attributes.user.email") %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="actions">
      <%= f.submit t('devise.passwords.new.send_me_reset_password_instructions') %>
    </div>
  <% end %>
</div>

FuzzydoDB/foroFuzzydoDB/app/views/shared/modals/_register.html.erb
<div ng-controller="RegistrationController">
<%# Rails sets default input names for each field (like user[name]),
  we adapt angular input name as follow: registrationForm['user[name]']%>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name),
  :html => {:class => "w3-container", :novalidate => true, "name" => "registrationForm"}) do |f| %>

  <div class="modal-body">

    <!-- name field -->

    <div class="field">
      <div id="regNameError" class="error-messages error" ng-messages="registrationForm['user[name]'].$error"
        ng-if="registrationForm['user[name]'].$touched || registrationForm.$submitted">
        <div ng-message="required"> <%= t("mongoid.errors.models.user.attributes.name.blank")%> </div>
      </div>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name, class: "w3-input",
            "ng-model" => "registerUser.name", "ng-model-options" => "{ updateOn: 'blur' }",
            :required => true %>
      </p>
      <span class="icon glyphicon"
        ng-class="{'error glyphicon-remove' : registrationForm['user[name]'].$invalid &&
          (registrationForm['user[name]'].$touched || registrationForm.$submitted),
          'sucess glyphicon-ok' : registrationForm['user[name]'].$valid}">
      </span>

    </div>

    <!-- username field -->

    <div class="field">
      <div id="regUsernameError" class="error-messages error" ng-messages="registrationForm['user[username]'].$error"
        ng-if="registrationForm['user[username]'].$touched || registrationForm.$submitted">
        <div ng-message="required"> <%= t("mongoid.errors.models.user.attributes.username.blank")%> </div>
        <div ng-message="usernameTaken"> <%= t("mongoid.errors.models.user.attributes.username.taken")%> </div>
        <div ng-message="pattern"><%= t("mongoid.errors.models.user.attributes.username.pattern")%></div>
      </div>
      <p>
        <%= f.label :username %>
        <%= f.text_field :username, class: "w3-input", "ng-model" => "registerUser.username",
        "ng-model-options" => "{ updateOn: 'blur' }", "username-taken-validator" => true,
        "ng-pattern" => "/^[a-zA-Z0-9_]*$/", :required => true %>
      </p>
      <span class="icon glyphicon"
        ng-class="{'error glyphicon-remove' : registrationForm['user[username]'].$invalid &&
          (registrationForm['user[username]'].$touched || registrationForm.$submitted),
          'sucess glyphicon-ok' : registrationForm['user[username]'].$valid,
          'icon-spin glyphicon-refresh' :  registrationForm['user[username]'].$pending}">
      </span>

    </div>

    <!-- email field -->

    <div class="field">
      <div id="regEmailError" class="error-messages error" ng-messages="registrationForm['user[email]'].$error"
        ng-if="registrationForm['user[email]'].$touched || registrationForm.$submitted">
        <div ng-message="required"> <%= t("mongoid.errors.models.user.attributes.email.blank")%> </div>
        <div ng-message="email"> <%= t("errors.invalidEmail") %> </div>
        <div ng-message="emailTaken"> <%= t("mongoid.errors.models.user.attributes.email.taken")%> </div>
      </div>
      <p>
        <%= f.label :email %>
        <%= f.email_field :email, class: "w3-input",
          "ng-model" => "registerUser.email", "ng-model-options" => "{ updateOn: 'blur' }",
          "email-taken-validator" => true, :required => true %>
      </p>
      <span class="icon glyphicon"
        ng-class="{'error glyphicon-remove' : registrationForm['user[email]'].$invalid &&
          (registrationForm['user[email]'].$touched || registrationForm.$submitted),
          'sucess glyphicon-ok' : registrationForm['user[email]'].$valid,
          'icon-spin glyphicon-refresh' :  registrationForm['user[email]'].$pending}">
      </span>

    </div>

    <!-- password field -->

    <div class="field">
      <div id="regPassWordError" class="error-messages error" ng-messages="registrationForm['user[password]'].$error"
        ng-if="registrationForm['user[password]'].$touched || registrationForm.$submitted">
        <div ng-message="required"> <%= t("mongoid.errors.models.user.attributes.password.blank")%> </div>
        <div ng-message="minlength"> <%= t("mongoid.errors.models.user.attributes.password.too_short")%> </div>
      </div>
      <p>
        <%= f.label :password %>
        <%= f.password_field :password, autocomplete: "off", class: "w3-input",
          "ng-model" => "registerUser.password", "ng-model-options" => "{ updateOn: 'blur' }",
          "ng-minlength" => 6, :required => true %>
      </p>

      <span class="icon glyphicon"
        ng-class="{'error glyphicon-remove' : registrationForm['user[password]'].$invalid &&
          (registrationForm['user[password]'].$touched || registrationForm.$submitted),
          'sucess glyphicon-ok' : registrationForm['user[password]'].$valid}">
      </span>

    </div>

    <!-- password confirmation field -->

    <div class="field">

      <div id="regPassWordConfirmationError" class="error-messages error"
        ng-messages="registrationForm['user[password_confirmation]'].$error"
        ng-if="registrationForm['user[password_confirmation]'].$touched || registrationForm.$submitted">
        <div ng-message="required"> <%= t("mongoid.errors.models.user.attributes.password.blank")%> </div>
        <div ng-message="equalPasswords">
          <%= t("mongoid.errors.models.user.attributes.password_confirmation.confirmation")%>
        </div>
      </div>

      <p>
        <%= f.label t("activerecord.attributes.user.password_confirmation") %>
        <%= f.password_field :password_confirmation, autocomplete: "off", class: "w3-input",
          "ng-model" => "registerUser.passwordConfirmation", "ng-model-options" => "{ updateOn: 'blur' }",
          "equal-passwords" => "registerUser.password", :required => true %>
      </p>

      <span class="icon glyphicon"
        ng-class="{'error glyphicon-remove' : registrationForm['user[password_confirmation]'].$invalid &&
          (registrationForm['user[password_confirmation]'].$touched || registrationForm.$submitted),
          'sucess glyphicon-ok' : registrationForm['user[password_confirmation]'].$valid}">
      </span>

    </div>

  </div>
  <div class="modal-footer">
    <div class="btn btn-non-primary" data-dismiss="modal"> <%= t("labels.cancel") %> </div>
    <%= f.submit t('devise.registrations.new.sign_up'), :id => "send-registration-btn",
      :class => "btn btn-default", "ng-click" => "submitRegistration($event)",
      "ng-disabled" => "registrationForm.$pending" %>
  </div>

<% end %>
</div>